import { strToU8, zipSync } from 'fflate'
import { buildDocx } from './docxBuilder'
import { buildPptx, escapeXml, textBox } from './pptxBuilder'

/**
 * A corpus of Arabic Office documents, generated by code so it can be regenerated at will (tests/unit/officeRtl*.test.ts
 * use it; `EPDF_WRITE_CORPUS=1 npx vitest run tests/unit/officeRtlCorpus.test.ts` writes the files, Epdf's PDFs and,
 * when LibreOffice is installed, LibreOffice's reference PDFs to test-results/office-rtl/).
 *
 * Every document lists the logical source strings of its paragraphs (`paras`) with the side their first line must be
 * aligned to (`side`, physical: what a reader sees), and whether the paragraph is short enough to fit on one line.
 */

export interface ExpectedPara {
  /** Logical text as typed (list markers included as they are read: marker, space, text). */
  text: string
  /** Physical side the paragraph's lines are aligned to (for justified paragraphs: the side of the last line). */
  side?: 'left' | 'right' | 'center'
  /** Fits on one line: the page text model must return exactly this line. */
  oneLine?: boolean
  /** Where the text is (body, header, footer, table). */
  where?: 'body' | 'header' | 'footer' | 'table' | 'cell' | 'tab'
}

export interface CorpusDoc {
  name: string
  bytes: Uint8Array
  paras: ExpectedPara[]
  /** Table/sheet header texts in LOGICAL column order (the first must be the rightmost in a right-to-left table). */
  columns?: string[]
}

// ---------------------------------------------------------------------------------------------------------------
// Texts

export const T = {
  title: 'تقرير الربع الأول',
  p1: 'مرحبا بالعالم. هذا مستند تجريبي لاختبار تحويل النصوص العربية إلى ملفات PDF.',
  p2a: 'تأسست شركة ',
  p2b: 'Epdf',
  p2c: ' في عام 2024 في المنامة، البحرين.',
  justify:
    'يهدف هذا المشروع إلى تطوير برنامج متكامل لتحرير ملفات المستندات وتحويلها، مع دعم كامل للغة العربية واتجاه الكتابة من اليمين إلى اليسار، بحيث تظهر الحروف متصلة بشكل صحيح وتبقى الكلمات بترتيبها المنطقي عند النسخ والبحث داخل الملف، سواء كان النص قصيرا أو طويلا يمتد على عدة أسطر.',
  end: 'هذه الفقرة محاذاة إلى النهاية.',
  center: 'فقرة في الوسط',
  bullets: ['البند الأول', 'البند الثاني', 'البند الثالث'],
  steps: ['الخطوة الأولى', 'الخطوة الثانية', 'الخطوة الثالثة'],
  abjad: ['أولا', 'ثانيا', 'ثالثا'],
  hindi: ['عنصر', 'عنصر آخر', 'عنصر أخير'],
  table: [
    ['الاسم', 'الكمية', 'السعر'],
    ['تفاح', '3', '1.250'],
    ['برتقال', '5', '2.500']
  ],
  tabA: 'البند',
  tabB: 'القيمة',
  indented: 'فقرة بمسافة بادئة من جهة البداية.',
  odtLeft: 'فقرة بمحاذاة إلى اليسار',
  odtRight: 'فقرة بمحاذاة إلى اليمين',
  big: 'نص كبير وعريض',
  english1: 'The capital of Bahrain is ',
  english2: 'المنامة',
  english3: ' and its currency is BHD.',
  latin: 'This paragraph is plain English text.',
  header: 'رأس الصفحة: تقرير تجريبي',
  footer: 'صفحة '
}

// ---------------------------------------------------------------------------------------------------------------
// DOCX

const W = 'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"'
const esc = escapeXml

/** Styles of an Arabic Word document: Times New Roman for Latin, Arial for Arabic (w:cs), 12 pt / 14 pt (szCs). */
const AR_STYLES = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles ${W}>
<w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman" w:eastAsia="Times New Roman" w:cs="Arial"/><w:sz w:val="24"/><w:szCs w:val="28"/><w:lang w:val="en-US" w:bidi="ar-BH"/></w:rPr></w:rPrDefault>
<w:pPrDefault><w:pPr><w:spacing w:after="120" w:line="240" w:lineRule="auto"/></w:pPr></w:pPrDefault></w:docDefaults>
<w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:qFormat/></w:style>
<w:style w:type="character" w:default="1" w:styleId="DefaultParagraphFont"><w:name w:val="Default Paragraph Font"/></w:style>
<w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:basedOn w:val="Normal"/><w:pPr><w:bidi/><w:jc w:val="center"/><w:spacing w:after="240"/></w:pPr><w:rPr><w:b/><w:bCs/><w:sz w:val="36"/><w:szCs w:val="40"/></w:rPr></w:style>
<w:style w:type="paragraph" w:styleId="ListParagraph"><w:name w:val="List Paragraph"/><w:basedOn w:val="Normal"/><w:pPr><w:ind w:left="720"/><w:contextualSpacing/></w:pPr></w:style>
<w:style w:type="table" w:default="1" w:styleId="TableNormal"><w:name w:val="Normal Table"/><w:tblPr><w:tblInd w:w="0" w:type="dxa"/><w:tblCellMar><w:top w:w="0" w:type="dxa"/><w:left w:w="108" w:type="dxa"/><w:bottom w:w="0" w:type="dxa"/><w:right w:w="108" w:type="dxa"/></w:tblCellMar></w:tblPr></w:style>
<w:style w:type="table" w:styleId="TableGrid"><w:name w:val="Table Grid"/><w:basedOn w:val="TableNormal"/><w:pPr><w:spacing w:after="0"/></w:pPr><w:tblPr><w:tblBorders><w:top w:val="single" w:sz="4" w:space="0" w:color="auto"/><w:left w:val="single" w:sz="4" w:space="0" w:color="auto"/><w:bottom w:val="single" w:sz="4" w:space="0" w:color="auto"/><w:right w:val="single" w:sz="4" w:space="0" w:color="auto"/><w:insideH w:val="single" w:sz="4" w:space="0" w:color="auto"/><w:insideV w:val="single" w:sz="4" w:space="0" w:color="auto"/></w:tblBorders></w:tblPr></w:style>
</w:styles>`

const lvl = (fmt: string, text: string, extra = ''): string =>
  `<w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="${fmt}"/><w:lvlText w:val="${text}"/><w:lvlJc w:val="left"/><w:pPr><w:ind w:left="720" w:hanging="360"/></w:pPr>${extra}</w:lvl>`
const AR_NUMBERING = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:numbering ${W}>
<w:abstractNum w:abstractNumId="0">${lvl('bullet', '•', '<w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial" w:cs="Arial"/></w:rPr>')}</w:abstractNum>
<w:abstractNum w:abstractNumId="1">${lvl('decimal', '%1.')}</w:abstractNum>
<w:abstractNum w:abstractNumId="2">${lvl('arabicAbjad', '%1-')}</w:abstractNum>
<w:abstractNum w:abstractNumId="3">${lvl('hindiNumbers', '%1.')}</w:abstractNum>
<w:num w:numId="1"><w:abstractNumId w:val="0"/></w:num><w:num w:numId="2"><w:abstractNumId w:val="1"/></w:num><w:num w:numId="3"><w:abstractNumId w:val="2"/></w:num><w:num w:numId="4"><w:abstractNumId w:val="3"/></w:num>
</w:numbering>`

const rr = (text: string, rpr = '<w:rtl/>'): string => `<w:r><w:rPr>${rpr}</w:rPr><w:t xml:space="preserve">${esc(text)}</w:t></w:r>`
/** pPr children in the order the schema requires (Word and LibreOffice ignore misplaced ones). */
const PPR_ORDER = ['pStyle', 'keepNext', 'keepLines', 'pageBreakBefore', 'widowControl', 'numPr', 'pBdr', 'shd', 'tabs', 'bidi', 'spacing', 'ind', 'contextualSpacing', 'jc']
const orderPPr = (xml: string): string =>
  (xml.match(/<w:(\w+)(?:[^>]*\/>|[^>]*>[\s\S]*?<\/w:\1>)/g) ?? [])
    .map((el) => ({ el, k: PPR_ORDER.indexOf(/^<w:(\w+)/.exec(el)![1]!) }))
    .sort((a, b) => a.k - b.k)
    .map((x) => x.el)
    .join('')
const bp = (runs: string, ppr = ''): string => `<w:p><w:pPr>${orderPPr('<w:bidi/>' + ppr)}</w:pPr>${runs}</w:p>`
const lp = (runs: string, ppr = ''): string => `<w:p><w:pPr>${orderPPr(ppr)}</w:pPr>${runs}</w:p>`
const item = (numId: number, text: string): string => bp(rr(text), `<w:pStyle w:val="ListParagraph"/><w:numPr><w:ilvl w:val="0"/><w:numId w:val="${numId}"/></w:numPr>`)

const arabicIndic = (n: number): string => String(n).replace(/[0-9]/g, (d) => String.fromCharCode(0x0660 + Number(d)))

export function docxDocument(opts: { pages?: number } = {}): CorpusDoc {
  const cell = (t: string, w: number): string => `<w:tc><w:tcPr><w:tcW w:w="${w}" w:type="dxa"/></w:tcPr>${bp(rr(t))}</w:tc>`
  const table =
    `<w:tbl><w:tblPr><w:tblStyle w:val="TableGrid"/><w:bidiVisual/><w:tblW w:w="0" w:type="auto"/><w:tblLook w:val="04A0"/></w:tblPr><w:tblGrid><w:gridCol w:w="3000"/><w:gridCol w:w="2000"/><w:gridCol w:w="2000"/></w:tblGrid>` +
    T.table.map((row) => `<w:tr>${row.map((t, i) => cell(t, i === 0 ? 3000 : 2000)).join('')}</w:tr>`).join('') +
    `</w:tbl>`
  const block = (k: number): string =>
    bp(rr(k ? `${T.title} ${k + 1}` : T.title), '<w:pStyle w:val="Title"/>') +
    bp(rr(T.p1), '<w:jc w:val="left"/>') +
    bp(rr(T.p2a) + rr(T.p2b, '<w:b/><w:bCs/>') + rr(T.p2c)) +
    bp(rr(T.justify), '<w:jc w:val="both"/>') +
    bp(rr(T.end), '<w:jc w:val="right"/>') +
    bp(rr(T.center), '<w:jc w:val="center"/>') +
    T.bullets.map((t) => item(1, t)).join('') +
    T.steps.map((t) => item(2, t)).join('') +
    T.abjad.map((t) => item(3, t)).join('') +
    T.hindi.map((t) => item(4, t)).join('') +
    table +
    bp(rr(T.tabA) + '<w:r><w:rPr><w:rtl/></w:rPr><w:tab/></w:r>' + rr(T.tabB), '<w:tabs><w:tab w:val="left" w:pos="2880"/></w:tabs><w:spacing w:before="240"/>') +
    bp(rr(T.indented), '<w:ind w:left="1440"/>') +
    bp(rr(T.big, '<w:rtl/><w:b/><w:bCs/><w:sz w:val="24"/><w:szCs w:val="40"/>')) +
    lp(rr(T.english1, '') + rr(T.english2) + rr(T.english3, '')) +
    lp(rr(T.latin, ''))
  const pages = opts.pages ?? 1
  let body = ''
  for (let k = 0; k < pages; k++) body += block(k) + (k + 1 < pages ? '<w:p><w:r><w:br w:type="page"/></w:r></w:p>' : '')
  const hdr = bp(rr(T.header), '<w:jc w:val="left"/>')
  const ftr = bp(rr(T.footer) + '<w:r><w:rPr><w:rtl/></w:rPr><w:fldChar w:fldCharType="begin"/></w:r><w:r><w:rPr><w:rtl/></w:rPr><w:instrText xml:space="preserve"> PAGE </w:instrText></w:r><w:r><w:rPr><w:rtl/></w:rPr><w:fldChar w:fldCharType="separate"/></w:r><w:r><w:rPr><w:rtl/></w:rPr><w:t>1</w:t></w:r><w:r><w:rPr><w:rtl/></w:rPr><w:fldChar w:fldCharType="end"/></w:r>', '<w:jc w:val="center"/>')
  const sect = `<w:sectPr><w:headerReference w:type="default" r:id="rId_header1.xml"/><w:footerReference w:type="default" r:id="rId_footer1.xml"/><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:header="708" w:footer="708" w:gutter="0"/><w:bidi/></w:sectPr>`
  const bytes = buildDocx({ body, sectPr: sect, styles: AR_STYLES, numbering: AR_NUMBERING, headers: { 'header1.xml': hdr }, footers: { 'footer1.xml': ftr } })
  const paras: ExpectedPara[] = [
    { text: T.title, side: 'center', oneLine: true },
    { text: T.p1, side: 'right' },
    { text: T.p2a + T.p2b + T.p2c, side: 'right', oneLine: true },
    { text: T.justify },
    { text: T.end, side: 'left', oneLine: true },
    { text: T.center, side: 'center', oneLine: true },
    ...T.bullets.map((t) => ({ text: `• ${t}`, side: 'right' as const, oneLine: true })),
    ...T.steps.map((t, i) => ({ text: `${i + 1}. ${t}`, side: 'right' as const, oneLine: true })),
    ...T.abjad.map((t, i) => ({ text: `${'أبج'[i]}- ${t}`, side: 'right' as const, oneLine: true })),
    ...T.hindi.map((t, i) => ({ text: `${arabicIndic(i + 1)}. ${t}`, side: 'right' as const, oneLine: true })),
    // a tab: the page text model reads the two sides of a wide tab gap as two pieces (column heuristic); the tab stop
    // position is checked against LibreOffice through the edge of the second piece
    { text: T.tabA, side: 'right', oneLine: true },
    { text: T.tabB, side: 'right', oneLine: true, where: 'tab' },
    { text: T.indented, side: 'right', oneLine: true },
    { text: T.big, side: 'right', oneLine: true },
    { text: T.english1 + T.english2 + T.english3, side: 'left', oneLine: true },
    { text: T.latin, side: 'left', oneLine: true },
    { text: T.header, side: 'right', oneLine: true, where: 'header' },
    { text: `${T.footer}1`, side: 'center', oneLine: true, where: 'footer' }
  ]
  return { name: pages > 1 ? `arabic-${pages}p.docx` : 'arabic.docx', bytes, paras, columns: T.table[0] }
}

// ---------------------------------------------------------------------------------------------------------------
// XLSX (right-to-left sheet)

export const SHEET = {
  header: ['المنتج', 'الكمية', 'السعر'],
  rows: [
    ['تفاح', 3, 1.25],
    ['برتقال', 5, 2.5],
    ['Total', 8, 3.75]
  ] as [string, number, number][],
  note: 'ملاحظة: الأسعار بالدينار البحريني (BHD)'
}

export function xlsxDocument(): CorpusDoc {
  const strings: string[] = []
  const si = (s: string): number => {
    const i = strings.indexOf(s)
    if (i >= 0) return i
    strings.push(s)
    return strings.length - 1
  }
  const c = (ref: string, v: string | number, s = 0): string => (typeof v === 'number' ? `<c r="${ref}" s="${s}"><v>${v}</v></c>` : `<c r="${ref}" s="${s}" t="s"><v>${si(v)}</v></c>`)
  const rows =
    `<row r="1">${SHEET.header.map((h, i) => c(`${'ABC'[i]}1`, h, 1)).join('')}</row>` +
    SHEET.rows.map((r, k) => `<row r="${k + 2}">${r.map((v, i) => c(`${'ABC'[i]}${k + 2}`, v)).join('')}</row>`).join('') +
    `<row r="6">${c('A6', SHEET.note)}</row>`
  const sheet = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView rightToLeft="1" tabSelected="1" workbookViewId="0"/></sheetViews><sheetFormatPr defaultRowHeight="15"/><cols><col min="1" max="1" width="18" customWidth="1"/><col min="2" max="3" width="12" customWidth="1"/></cols><sheetData>${rows}</sheetData><pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3"/><pageSetup paperSize="9" orientation="portrait"/></worksheet>`
  const sst = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="${strings.length}" uniqueCount="${strings.length}">${strings.map((s) => `<si><t xml:space="preserve">${esc(s)}</t></si>`).join('')}</sst>`
  const styles = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Arial"/></font><font><b/><sz val="11"/><name val="Arial"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0" applyFont="1"/></cellXfs></styleSheet>`
  const wb = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="المبيعات" sheetId="1" r:id="rId1"/></sheets></workbook>`
  const REL = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships'
  const files = {
    '[Content_Types].xml': strToU8(
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/sharedStrings.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>'
    ),
    '_rels/.rels': strToU8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="${REL}/officeDocument" Target="xl/workbook.xml"/></Relationships>`),
    'xl/workbook.xml': strToU8(wb),
    'xl/_rels/workbook.xml.rels': strToU8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="${REL}/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="${REL}/sharedStrings" Target="sharedStrings.xml"/><Relationship Id="rId3" Type="${REL}/styles" Target="styles.xml"/></Relationships>`),
    'xl/worksheets/sheet1.xml': strToU8(sheet),
    'xl/sharedStrings.xml': strToU8(sst),
    'xl/styles.xml': strToU8(styles)
  }
  const paras: ExpectedPara[] = [...SHEET.header, ...SHEET.rows.map((r) => r[0]), SHEET.note].map((t) => ({ text: t, oneLine: true, where: 'cell' as const }))
  return { name: 'arabic.xlsx', bytes: zipSync(files), paras, columns: SHEET.header }
}

// ---------------------------------------------------------------------------------------------------------------
// ODS (right-to-left table)

export function odsDocument(): CorpusDoc {
  const cellS = (t: string, style = ''): string => `<table:table-cell office:value-type="string"${style ? ` table:style-name="${style}"` : ''}><text:p>${esc(t)}</text:p></table:table-cell>`
  const cellN = (n: number): string => `<table:table-cell office:value-type="float" office:value="${n}"><text:p>${n}</text:p></table:table-cell>`
  const rows =
    `<table:table-row>${SHEET.header.map((h) => cellS(h, 'ceB')).join('')}</table:table-row>` +
    SHEET.rows.map((r) => `<table:table-row>${cellS(r[0])}${cellN(r[1])}${cellN(r[2])}</table:table-row>`).join('') +
    `<table:table-row>${cellS(SHEET.note)}</table:table-row>`
  const NS =
    'xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0" xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0" xmlns:table="urn:oasis:names:tc:opendocument:xmlns:table:1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:svg="urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0" office:version="1.3"'
  const content = `<?xml version="1.0" encoding="UTF-8"?><office:document-content ${NS}><office:font-face-decls><style:font-face style:name="Arial" svg:font-family="Arial" style:font-family-generic="swiss"/></office:font-face-decls><office:automatic-styles><style:style style:name="co1" style:family="table-column"><style:table-column-properties style:column-width="4cm"/></style:style><style:style style:name="co2" style:family="table-column"><style:table-column-properties style:column-width="2.5cm"/></style:style><style:style style:name="ta1" style:family="table" style:master-page-name="Default"><style:table-properties table:display="true" style:writing-mode="rl-tb"/></style:style><style:style style:name="ceB" style:family="table-cell"><style:text-properties fo:font-weight="bold" style:font-weight-complex="bold"/></style:style></office:automatic-styles><office:body><office:spreadsheet><table:table table:name="المبيعات" table:style-name="ta1"><table:table-column table:style-name="co1"/><table:table-column table:style-name="co2" table:number-columns-repeated="2"/>${rows}</table:table></office:spreadsheet></office:body></office:document-content>`
  const styles = `<?xml version="1.0" encoding="UTF-8"?><office:document-styles ${NS}><office:font-face-decls><style:font-face style:name="Arial" svg:font-family="Arial" style:font-family-generic="swiss"/></office:font-face-decls><office:styles><style:default-style style:family="table-cell"><style:text-properties style:font-name="Arial" fo:font-size="10pt" style:font-name-complex="Arial" style:font-size-complex="10pt"/></style:default-style></office:styles><office:automatic-styles><style:page-layout style:name="pm1"><style:page-layout-properties fo:page-width="21cm" fo:page-height="29.7cm" fo:margin-top="2cm" fo:margin-bottom="2cm" fo:margin-left="2cm" fo:margin-right="2cm" style:writing-mode="rl-tb"/><style:header-style/><style:footer-style/></style:page-layout></office:automatic-styles><office:master-styles><style:master-page style:name="Default" style:page-layout-name="pm1"><style:header style:display="false"/><style:footer style:display="false"/></style:master-page></office:master-styles></office:document-styles>`
  const bytes = odfPackage('application/vnd.oasis.opendocument.spreadsheet', content, styles)
  const paras: ExpectedPara[] = [...SHEET.header, ...SHEET.rows.map((r) => r[0]), SHEET.note].map((t) => ({ text: t, oneLine: true, where: 'cell' as const }))
  return { name: 'arabic.ods', bytes, paras, columns: SHEET.header }
}

function odfPackage(mime: string, content: string, styles: string): Uint8Array {
  const files: Record<string, Uint8Array | [Uint8Array, { level: 0 }]> = {
    mimetype: [strToU8(mime), { level: 0 }],
    'META-INF/manifest.xml': strToU8(
      `<?xml version="1.0" encoding="UTF-8"?><manifest:manifest xmlns:manifest="urn:oasis:names:tc:opendocument:xmlns:manifest:1.0" manifest:version="1.3"><manifest:file-entry manifest:full-path="/" manifest:version="1.3" manifest:media-type="${mime}"/><manifest:file-entry manifest:full-path="content.xml" manifest:media-type="text/xml"/><manifest:file-entry manifest:full-path="styles.xml" manifest:media-type="text/xml"/></manifest:manifest>`
    ),
    'content.xml': strToU8(content),
    'styles.xml': strToU8(styles)
  }
  return zipSync(files as never)
}

// ---------------------------------------------------------------------------------------------------------------
// ODT

export function odtDocument(): CorpusDoc {
  const NS =
    'xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0" xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0" xmlns:table="urn:oasis:names:tc:opendocument:xmlns:table:1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:svg="urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0" office:version="1.3"'
  const fonts = `<office:font-face-decls><style:font-face style:name="Liberation Serif" svg:font-family="'Liberation Serif'" style:font-family-generic="roman"/><style:font-face style:name="Arial" svg:font-family="Arial" style:font-family-generic="swiss"/></office:font-face-decls>`
  const pstyle = (name: string, align: string, extra = ''): string =>
    `<style:style style:name="${name}" style:family="paragraph" style:parent-style-name="Standard"><style:paragraph-properties fo:text-align="${align}" style:writing-mode="rl-tb"${extra}/></style:style>`
  const auto =
    pstyle('PS', 'start') +
    pstyle('PE', 'end') +
    pstyle('PC', 'center') +
    pstyle('PJ', 'justify') +
    pstyle('PI', 'start', ' fo:margin-left="2cm" fo:margin-right="0cm"') +
    pstyle('PL2', 'left') +
    pstyle('PR2', 'right') +
    `<style:style style:name="PL" style:family="paragraph" style:parent-style-name="Standard"><style:paragraph-properties fo:text-align="start" style:writing-mode="lr-tb"/></style:style>` +
    `<style:style style:name="TB" style:family="text"><style:text-properties fo:font-weight="bold" style:font-weight-complex="bold" style:font-size-complex="18pt"/></style:style>` +
    `<style:style style:name="Tab1" style:family="table"><style:table-properties style:width="12cm" table:align="right" style:writing-mode="rl-tb"/></style:style>` +
    `<style:style style:name="Tab1.A" style:family="table-column"><style:table-column-properties style:column-width="4cm"/></style:style>` +
    `<style:style style:name="Cell" style:family="table-cell"><style:table-cell-properties fo:padding="0.1cm" fo:border="0.5pt solid #000000"/></style:style>`
  const p = (style: string, text: string): string => `<text:p text:style-name="${style}">${text}</text:p>`
  const tableXml =
    `<table:table table:name="T1" table:style-name="Tab1"><table:table-column table:style-name="Tab1.A" table:number-columns-repeated="3"/>` +
    T.table.map((row) => `<table:table-row>${row.map((t) => `<table:table-cell table:style-name="Cell" office:value-type="string">${p('PS', esc(t))}</table:table-cell>`).join('')}</table:table-row>`).join('') +
    `</table:table>`
  const body =
    p('PC', esc(T.title)) +
    p('PS', esc(T.p1)) +
    p('PS', esc(T.p2a) + `<text:span text:style-name="TB">${esc(T.p2b)}</text:span>` + esc(T.p2c)) +
    p('PJ', esc(T.justify)) +
    p('PE', esc(T.end)) +
    p('PC', esc(T.center)) +
    p('PL2', esc(T.odtLeft)) +
    p('PR2', esc(T.odtRight)) +
    tableXml +
    p('PI', esc(T.indented)) +
    p('PS', `<text:span text:style-name="TB">${esc(T.big)}</text:span>`) +
    p('PL', esc(T.english1 + T.english2 + T.english3)) +
    p('PL', esc(T.latin))
  const content = `<?xml version="1.0" encoding="UTF-8"?><office:document-content ${NS}>${fonts}<office:automatic-styles>${auto}</office:automatic-styles><office:body><office:text>${body}</office:text></office:body></office:document-content>`
  const styles = `<?xml version="1.0" encoding="UTF-8"?><office:document-styles ${NS}>${fonts}<office:styles><style:default-style style:family="paragraph"><style:paragraph-properties style:tab-stop-distance="1.25cm" style:writing-mode="page"/><style:text-properties style:font-name="Liberation Serif" fo:font-size="12pt" style:font-name-complex="Arial" style:font-size-complex="14pt"/></style:default-style><style:style style:name="Standard" style:family="paragraph" style:class="text"><style:paragraph-properties fo:margin-bottom="0.2cm"/></style:style></office:styles><office:automatic-styles><style:page-layout style:name="Mpm1"><style:page-layout-properties fo:page-width="21cm" fo:page-height="29.7cm" fo:margin-top="2cm" fo:margin-bottom="2cm" fo:margin-left="2cm" fo:margin-right="2cm" style:writing-mode="rl-tb"/></style:page-layout></office:automatic-styles><office:master-styles><style:master-page style:name="Standard" style:page-layout-name="Mpm1"/></office:master-styles></office:document-styles>`
  const bytes = odfPackage('application/vnd.oasis.opendocument.text', content, styles)
  const paras: ExpectedPara[] = [
    { text: T.title, side: 'center', oneLine: true },
    { text: T.p1, side: 'right' },
    { text: T.p2a + T.p2b + T.p2c, side: 'right', oneLine: true },
    { text: T.justify },
    { text: T.end, side: 'left', oneLine: true },
    { text: T.center, side: 'center', oneLine: true },
    { text: T.odtLeft, side: 'left', oneLine: true },
    { text: T.odtRight, side: 'right', oneLine: true },
    ...T.table.flat().map((t) => ({ text: t, oneLine: true, where: 'table' as const })),
    { text: T.indented, side: 'right', oneLine: true },
    { text: T.big, side: 'right', oneLine: true },
    { text: T.english1 + T.english2 + T.english3, side: 'left', oneLine: true },
    { text: T.latin, side: 'left', oneLine: true }
  ]
  return { name: 'arabic.odt', bytes, paras, columns: T.table[0] }
}

// ---------------------------------------------------------------------------------------------------------------
// RTF

const rtfText = (s: string): string =>
  Array.from(s)
    .map((ch) => {
      const cp = ch.codePointAt(0)!
      if (ch === '\\' || ch === '{' || ch === '}') return '\\' + ch
      if (cp < 128) return ch
      return `\\u${cp > 32767 ? cp - 65536 : cp}?`
    })
    .join('')

export function rtfDocument(): CorpusDoc {
  const ar = (t: string, extra = ''): string => `{\\rtlch\\fcs1\\af1\\afs28${extra} \\ltrch\\fcs0\\f0\\fs24 ${rtfText(t)}}`
  const en = (t: string, extra = ''): string => `{\\ltrch\\fcs0\\f0\\fs24${extra} ${rtfText(t)}}`
  const para = (align: string, content: string, dir = '\\rtlpar'): string => `\\pard\\plain ${dir}\\${align}\\sa120 ${content}\\par\n`
  const body =
    para('qc', ar(T.title, '\\ab')) +
    para('qr', ar(T.p1)) +
    para('qr', ar(T.p2a) + en(T.p2b, '\\b') + ar(T.p2c)) +
    para('qj', ar(T.justify)) +
    para('ql', ar(T.end)) +
    para('qc', ar(T.center)) +
    para('qr', ar(T.big, '\\ab\\afs40')) +
    para('ql', en(T.english1) + ar(T.english2) + en(T.english3), '\\ltrpar') +
    para('ql', en(T.latin), '\\ltrpar')
  const doc = `{\\rtf1\\ansi\\ansicpg1256\\deff0\\adeff1{\\fonttbl{\\f0\\froman\\fcharset0 Times New Roman;}{\\f1\\fswiss\\fcharset178 Arial;}}\\paperw11906\\paperh16838\\margl1440\\margr1440\\margt1440\\margb1440\\rtlsect\n${body}}`
  const paras: ExpectedPara[] = [
    { text: T.title, side: 'center', oneLine: true },
    { text: T.p1, side: 'right' },
    { text: T.p2a + T.p2b + T.p2c, side: 'right', oneLine: true },
    { text: T.justify },
    { text: T.end, side: 'left', oneLine: true },
    { text: T.center, side: 'center', oneLine: true },
    { text: T.big, side: 'right', oneLine: true },
    { text: T.english1 + T.english2 + T.english3, side: 'left', oneLine: true },
    { text: T.latin, side: 'left', oneLine: true }
  ]
  return { name: 'arabic.rtf', bytes: strToU8(doc), paras }
}

// ---------------------------------------------------------------------------------------------------------------
// PPTX / ODP

export const SLIDE = {
  title: 'عرض تقديمي باللغة العربية',
  right: 'فقرة بمحاذاة اليمين',
  left: 'فقرة بمحاذاة اليسار',
  center: 'فقرة في الوسط',
  bullet: 'نقطة أولى في القائمة',
  mixed: 'الإصدار 2.0 من Epdf متوفر الآن',
  english: 'An English paragraph on the same slide'
}

export function pptxDocument(): CorpusDoc {
  const ap = (text: string, ppr: string, rpr = '<a:cs typeface="Arial"/>'): string => `<a:p><a:pPr ${ppr}/><a:r><a:rPr lang="ar-BH" sz="2400">${rpr}</a:rPr><a:t>${esc(text)}</a:t></a:r></a:p>`
  const bullet = `<a:p><a:pPr rtl="1" algn="r" marL="342900" indent="-342900"><a:buFont typeface="Arial"/><a:buChar char="•"/></a:pPr><a:r><a:rPr lang="ar-BH" sz="2400"><a:cs typeface="Arial"/></a:rPr><a:t>${esc(SLIDE.bullet)}</a:t></a:r></a:p>`
  const shapes =
    textBox(2, 457200, 300000, 8229600, 900000, [`<a:p><a:pPr rtl="1" algn="ctr"/><a:r><a:rPr lang="ar-BH" sz="3600" b="1"><a:cs typeface="Arial"/></a:rPr><a:t>${esc(SLIDE.title)}</a:t></a:r></a:p>`]) +
    textBox(3, 457200, 1400000, 8229600, 4000000, [ap(SLIDE.right, 'rtl="1" algn="r"'), ap(SLIDE.left, 'rtl="1" algn="l"'), ap(SLIDE.center, 'rtl="1" algn="ctr"'), bullet, ap(SLIDE.mixed, 'rtl="1" algn="r"'), `<a:p><a:pPr algn="l"/><a:r><a:rPr lang="en-US" sz="2400"/><a:t>${esc(SLIDE.english)}</a:t></a:r></a:p>`])
  const bytes = buildPptx({ slides: [{ shapes }] })
  const paras: ExpectedPara[] = [
    { text: SLIDE.title, side: 'center', oneLine: true },
    { text: SLIDE.right, side: 'right', oneLine: true },
    { text: SLIDE.left, side: 'left', oneLine: true },
    { text: SLIDE.center, side: 'center', oneLine: true },
    { text: `• ${SLIDE.bullet}`, side: 'right', oneLine: true },
    { text: SLIDE.mixed, side: 'right', oneLine: true },
    { text: SLIDE.english, side: 'left', oneLine: true }
  ]
  return { name: 'arabic.pptx', bytes, paras }
}

// ---------------------------------------------------------------------------------------------------------------
// TXT / CSV

export const TXT = [
  'هذا ملف نصي عادي باللغة العربية.',
  'This line is English.',
  'السطر الثالث يحتوي على رقم 42 وكلمة Epdf.',
  'The fourth line mentions المنامة in the middle.',
  'آخر سطر في الملف.'
]

export const CSV = [
  ['الاسم', 'المدينة', 'العمر'],
  ['أحمد', 'المنامة', '34'],
  ['فاطمة', 'المحرق', '29'],
  ['John', 'Riffa', '41']
]

export function txtDocument(): CorpusDoc {
  const paras: ExpectedPara[] = TXT.map((t) => ({ text: t, oneLine: true, side: /^[؀-ۿ]/.test(t) ? 'right' : 'left' }))
  return { name: 'arabic.txt', bytes: strToU8(TXT.join('\n') + '\n'), paras }
}

export function csvDocument(): CorpusDoc {
  const paras: ExpectedPara[] = CSV.flat()
    .filter((t) => !/^\d+$/.test(t))
    .map((t) => ({ text: t, oneLine: true, where: 'cell' as const }))
  return { name: 'arabic.csv', bytes: strToU8(CSV.map((r) => r.join(',')).join('\n') + '\n'), paras, columns: CSV[0] }
}

export function allCorpus(): CorpusDoc[] {
  return [docxDocument(), xlsxDocument(), odsDocument(), odtDocument(), rtfDocument(), pptxDocument(), txtDocument(), csvDocument()]
}
